version: "3"
services:
  redis:
    image: redis:alpine
    container_name: laravel-9-vite-crud-redis
    ports:
      - "6380:6379"

  php:
    build:
      context: ./
      dockerfile: app.dockerfile
    image: php:8.1-fpm
    container_name: php-8
    volumes:
      - ./:/var/www/html

  webserver:
    image: nginx:1.17.10
    container_name: nginx-webserver
    links:
      - php:fpm
    environment:
      - FPM_HOST=fpm
      - FPM_PORT=9000
    volumes:
      - ./:/var/www/html
      - ./docker/nginx_conf:/etc/nginx/conf.d/
    ports:
      - "8080:80"

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampleDB
      MYSQL_USER: namdv
      MYSQL_PASSWORD: namdv123
    ports:
      - 3308:3306
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
