version: '3'
services:
    app:
        build:
            context: ./docker/app
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www/html

    redis:
        image: redis:latest
        ports:
            - ${DOCKER_REDIS_EXTERNAL_PORT-6379}:6379
        networks:
            - backend

    mysql:
        image: mysql:8.0
        volumes:
            - mysqldb:/var/lib/mysql
        environment:
            MYSQL_USER: ipcc_user
            MYSQL_DATABASE: ipcc_be_db
            MYSQL_PASSWORD: ipcc_pass
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3309:3306"
        command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        networks:
            - backend

volumes:
    mysqldb:
        driver: local

networks:
    backend:
        driver: "bridge"